/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2b10f906-4124-4c34-9eee-d931df153b75",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lDhM7ddym",
    "aws_user_pools_web_client_id": "7jvq42l4hqtn2ppd4h0bkeurq6",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "myjotbot_chatbot_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ],
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
